@include('common.css')
@include('common.topHeader')
@include('common.navbar')
@include('common.fullSearch')
@include('common.facts')
@include('common.about')

@include('common.feature')
@include('common.service')
@include('common.pricing')
@include('common.quate')
@include('common.testmonial')
@include('common.team')
@include('common.blog')
@include('common.vender')
@include('common.footer')
@include('common.scripts')