on:
  push:
      branches:
      - master
name:  Deploy website on push
jobs:
  web-deploy:
    name:  Deploy
    runs-on: ubuntu-latest
    steps:
    - name:  Get latest code
      uses: actions/checkout@v4
    
    - name:  Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: 82.112.229.9
        username: u898003757.guri
        password: Guri@4321#
        server-dir: /your/server/directory # Update this path with your actual server directory path
        local-dir: ./  # Update with your local project directory (usually root of the project)
        exclude: |
            /resources/views/common  # Exclude the non-existent directory
            .git*
            .env
            node_modules/
            vendor/
